### PR TITLE
Fixed b.hasOwnProperty issue

### PR DESCRIPTION
**Pull request by troykelly**
TypeError: b.hasOwnProperty is not a function

### CODE REVIEW

**Comment by MrSwitch** [comment]
Thanks, can you provide a little information about how and when this error occurs?

**Comment by troykelly** [comment]
I was getting the error at the line I changed, I think it's a NodeJS version incompatibility / change.
I'm going to close this pull request because it's turned into a bigger project of adding database support.

**Comment by MrSwitch** [comment]
Yes FYI you should not modify this library to add db support, but rather redefined `oauthshim.credentials.get` as described in https://github.com/MrSwitch/node-oauth-shim#asynchronsly-retrieve-the-secret

**Comment by troykelly** [comment]
Ah - ok - I thought oauthshim.credentials.get was for getting the credentials of the service (twitter etc).

**Pull request closed without merging**
